### ISSUE TITLE
twilio@4.0.1: decompress error

### ISSUE THREAD

**Issue by osase7** [twilio/scoop-twilio-cli#13]
Hello team,

Kindly assist to look into this.
Find the error below,

Failed to extract files from C:\Users\hp\scoop\apps\twilio\4.0.1\\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\4.0.1\\7zip.log

**Comment by shrutiburman** [comment]
Hi @osase7, Thanks for reaching out. We've identified this issue internally and are working on it. Meanwhile, to unblock you can download the updated cli version from releases executables present [here](https://github.com/twilio/twilio-cli/releases/tag/4.0.1#:~:text=12%20days%20ago-,twilio%2D4.0.1.exe,-46.3%20MB).

**Comment by shrutiburman** [comment]
Hi @osase7 ,
This has been fixed in our latest release 🚀.
Closing this issue, feel free to re-open if you're still facing this. 

![Screenshot 2022-08-25 at 12 16 06 PM](https://user-images.githubusercontent.com/87537688/186598439-88aa8cdc-ae47-4326-a947-eb9f823aa2ae.png)
