### ISSUE TITLE
twilio@5.18.0: decompress error

### ISSUE THREAD

**Issue by HaarisHuda** [twilio/scoop-twilio-cli#160]
Failed to extract files from C:\Users\haari\scoop\apps\twilio\5.18.0\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.18.0\7zip.log

**Comment by kridai** [comment]
please make sure you are running the command as an administrator as mentioned [here](https://github.com/twilio/scoop-twilio-cli?tab=readme-ov-file#installation-instructions)
