### ISSUE TITLE
twilio@4.1.0: decompress error

### ISSUE THREAD

**Issue by AriRoxx** [twilio/scoop-twilio-cli#17]
Failed to extract files from C:\Users\docto\scoop\apps\twilio\4.1.0\\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\4.1.0\\7zip.log

**Comment by shrutiburman** [comment]
Hi @AriRoxx  , Thanks for reaching out. I tried replicating this issue but didn't get any errors. Can you try uninstalling twilio cache (if you've installed it before ever)? 
Execute: 
`scoop uninstall twilio`
`scoop install twilio` 

![Screenshot 2022-08-31 at 10 54 35 AM](https://user-images.githubusercontent.com/87537688/187604417-34e5af37-48da-45b3-9036-6ee5b34f3a29.png)

**Comment by shrutiburman** [comment]
Closed due to inactivity.
