### ISSUE TITLE
twilio@4.1.0: decompress error - ERROR Exit code was 2! 

### ISSUE THREAD

**Issue by NandaJS** [twilio/scoop-twilio-cli#18]
Hi All, somebody please help me. 
I am not able to install the 'twilio' app using scoop. Its failing to extract the file.

Bellow is the screenshot of the logs.

<img width="805" alt="Scoop error" src="https://user-images.githubusercontent.com/14902276/187251246-1ced3b2c-a7e2-4304-b6a2-eed16a0d32be.png">

**Comment by shrutiburman** [comment]
Hi @NandaJS , Thanks for reaching out. I tried replicating this issue but didn't get any errors. Can you try uninstalling twilio cache (if you've installed it before ever)? 
Execute: 
`scoop uninstall twilio`
`scoop install twilio` 

![Screenshot 2022-08-31 at 10 54 35 AM](https://user-images.githubusercontent.com/87537688/187604417-34e5af37-48da-45b3-9036-6ee5b34f3a29.png)

**Comment by NandaJS** [comment]
Hi @shrutiburman, I tried uninstalling and installed again. Still I am facing the same issue.

Bellow is the screen shot of console ->

<img width="562" alt="twilio installation error" src="https://user-images.githubusercontent.com/14902276/187958891-9a0ea3a9-18b5-4ab9-be66-6410855f01af.png">

Please help in fixing it if somebody knows the solution.

**Comment by ChaplinBW** [comment]
I have the exact same issue. I don't have a clue on what could have gone wrong :(

**Comment by ChaplinBW** [comment]
Okay, so the fix was opening the Windows PowerShell as an administrator! That works for me :)

**Comment by shrutiburman** [comment]
Awesome! Marking this as resolved.
