### ISSUE TITLE
twilio@4.1.0: decompress error

### ISSUE THREAD

**Issue by tanbeast** [twilio/scoop-twilio-cli#19]
Failed to extract files from C:\Users\ocrow\scoop\apps\twilio\4.1.0\\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\4.1.0\\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%404.1.0%3a+decompress+error

**Comment by shrutiburman** [comment]
Hi @tanbeast , Thanks for reaching out. I tried replicating this issue but didn't get any errors. Can you try uninstalling twilio cache (if you've installed it before ever)? 
Execute: 
`scoop uninstall twilio`
`scoop install twilio` 

![Screenshot 2022-08-31 at 10 54 35 AM](https://user-images.githubusercontent.com/87537688/187604417-34e5af37-48da-45b3-9036-6ee5b34f3a29.png)

**Comment by shrutiburman** [comment]
Hey @tanbeast I am assuming you're following all the instructions from our [quickstart](https://www.twilio.com/docs/twilio-cli/quickstart#install-using-scoop) guide? The powershell needs to be ran in *admin mode*

**Comment by shrutiburman** [comment]
Closed due to inactivity.
