### ISSUE TITLE
twilio@4.2.0: decompress error

### ISSUE THREAD

**Issue by andrew-wiskus** [twilio/scoop-twilio-cli#21]
```
Failed to extract files from C:\Users\redacted\scoop\apps\twilio\4.2.0\\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\4.2.0\\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
```

:( I'm following the CLI guide from: https://www.twilio.com/docs/sms/quickstart/node#receive-and-reply-to-inbound-sms-messages-with-express

**Comment by dwexel** [comment]
same issue for me.

**Comment by shrutiburman** [comment]
Hey @andrew-wiskus & @dwexel, 
Hope you're using Powershell **as an Admin**, that's an important step.
