### ISSUE TITLE
twilio@5.22.5: decompress error

### ISSUE THREAD

**Issue by AhsanRHusain** [twilio/scoop-twilio-cli#216]
PS C:\Users\Ahsan.Husain> scoop install twilio
Installing 'twilio' (5.22.5) [64bit] from 'twilio-scoop' bucket
twilio-win32-x64.tar.xz (42.2 MB) [===========================================================================] 100%
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Ahsan.Husain\scoop\apps\twilio\5.22.5\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.22.5\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.22.5%3a+decompress+error
PS C:\Users\Ahsan.Husain> twilio login
twilio : The term 'twilio' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling
of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ twilio login
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (twilio:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\Ahsan.Husain> scoop install twilio
WARN  Purging previous failed installation of twilio.
ERROR 'twilio' isn't installed correctly.
Removing older version (5.22.5).
'twilio' was uninstalled.
Installing 'twilio' (5.22.5) [64bit] from 'twilio-scoop' bucket
Loading twilio-win32-x64.tar.xz from cache
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Ahsan.Husain\scoop\apps\twilio\5.22.5\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.22.5\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.22.5%3a+decompress+error

**Comment by BPTwilio** [comment]
Hi Ahsan!  I was just wondering how you solved this.  I am going through the same thing.
