### ISSUE TITLE
twilio@4.2.0: decompress error

### ISSUE THREAD

**Issue by damasiorafael** [twilio/scoop-twilio-cli#23]
I have this issue since yesterday, I tried too way to install, with power shell with administrator mode and with power shell without administrator mode. Can you help me? I need to do some work for my employee. Thank you a lot!

The error message: https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%404.2.0%3a+decompress+error

**Comment by shrutiburman** [comment]
Hi @damasiorafael , Thanks for reaching out. I am guessing you're using `scoop install twilio` on Powershell as an admin.
Can you help us with a screenshot of the error ?
Meanwhile, to unblock you, you can also download the exe file directly, from [here](https://github.com/twilio/twilio-cli/releases/tag/5.0.0#:~:text=23%20hours%20ago-,twilio%2D5.0.0.exe,-46.9%20MB) .
