### ISSUE TITLE
twilio@5.0.0: decompress error

### ISSUE THREAD

**Issue by test451ks** [twilio/scoop-twilio-cli#24]
Got an error on Windows 11:

 scoop install twilio
WARN  Purging previous failed installation of twilio.
ERROR 'twilio' isn't installed correctly.
Removing older version (5.0.0).
'twilio' was uninstalled.
Installing 'twilio' (5.0.0) [64bit] from twilio-scoop bucket
Loading twilio-win32-x64.tar.xz from cache
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\############\scoop\apps\twilio\5.0.0\\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.0.0\\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.0.0%3a+decompress+error

**Comment by shrutiburman** [comment]
Hi @test451ks, Thanks for reaching out. Are you running **Powershell as an Admin** ? 
Couldn't replicate the issue in my box: 
![Screenshot 2022-09-20 at 10 31 45 AM](https://user-images.githubusercontent.com/87537688/191172598-62f72c5d-6caa-45ec-969b-f4230d2a1c1a.png)
