### ISSUE TITLE
twilio@5.0.0: decompress error

### ISSUE THREAD

**Issue by mildiasjr** [twilio/scoop-twilio-cli#26]
I cannot install Twilio CLI with: 

PS C:\Users\Milton Dias> **scoop install twilio**

WARN  Purging previous failed installation of twilio.
ERROR 'twilio' isn't installed correctly.
Removing older version (5.0.0).
'twilio' was uninstalled.
Installing 'twilio' (5.0.0) [64bit] from twilio-scoop bucket
Loading twilio-win32-x64.tar.xz from cache
Checking hash of twilio-win32-x64.tar.xz ... ok.
**Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Milton Dias\scoop\apps\twilio\5.0.0\\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.0.0\\7zip.log**

**Comment by shrutiburman** [comment]
Hi @mildiasjr , Thanks for reaching out. Can you try this while running **"Powershell as an Admin"** ?

**Comment by mildiasjr** [comment]
Hi. Indeed. I ran Powershell as admin and it step over the issue. Thanks. 
It was a little tricky. Because, I should try two ways to solve the issue.  That was my path to solve the entire installation of Twilio-CLI. 
CMD
C:/>powershell
PS C:\Users\Milton Dias> Set-ExecutionPolicy RemoteSigned -scope CurrentUser
PS C:\Users\Milton Dias> iwr -useb get.scoop.sh | iex
PS C:\Users\Milton Dias> scoop install git
And then, the last step, because the error indicated above, I tried Powershell on Windows, running as Admin. I ran:
 - scoop install twilio
 I should try the one and other to avoid the errors.

**Comment by shrutiburman** [comment]
Awesome! I see you had to install scoop before installing twilio-cli. FYI, You could've also used the executable that we ship with each release, [here](https://github.com/twilio/twilio-cli/releases/tag/5.0.0#:~:text=8%20days%20ago-,twilio%2D5.0.0.exe,-46.9%20MB). 
I'd go ahead and close this issue, please feel free to re-open should you need any further help.
