### ISSUE TITLE
twilio@5.2.1: decompress error

### ISSUE THREAD

**Issue by ttrejosgUam** [twilio/scoop-twilio-cli#35]
Failed to extract files from C:\Users\Jaime\scoop\apps\twilio\5.2.1\\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.2.1\\7zip.log

**Comment by kridai** [comment]
Hi @ttrejosgUam , Thanks for posting this.
Can you please try running Powershell as an Admin ?
