### ISSUE TITLE
twilio@5.2.2: decompress error

### ISSUE THREAD

**Issue by tyler-knapp** [twilio/scoop-twilio-cli#37]
Hello,

Getting the below error. Wondering what the work around is here...

Installing 'twilio' (5.2.2) [64bit] from twilio-scoop bucket
twilio-win32-x64.tar.xz (32.5 MB) [===========================================================================] 100%
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\tyler\scoop\apps\twilio\5.2.2\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.2.2\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.2.2%3a+decompress+error

**Comment by shrutiburman** [comment]
Hey @tyler-knapp! Thanks for reaching out. 
This looks like a duplicate issue. 
Please try running this cmd in **Powershell ran as an Admin**.
