### ISSUE TITLE
twilio@5.2.2: decompress error

### ISSUE THREAD

**Issue by IVL14** [twilio/scoop-twilio-cli#38]
Hello, I am trying to install twilio and I have the following error decompressing:

Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\User\scoop\apps\twilio\5.2.2\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.2.2\7zip.log

**Comment by shrutiburman** [comment]
Hi @IVL14 ! 
This looks like a duplicate issue.
Please try running this cmd in Powershell ran as an Admin
