### ISSUE TITLE
twilio@5.2.3: decompress error

### ISSUE THREAD

**Issue by ppam123** [twilio/scoop-twilio-cli#39]
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\erikd\scoop\apps\twilio\5.2.3\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.2.3\7zip.log

**Comment by ppam123** [comment]
I'm on Windows and running Powershell as admin. Wondering what the issue might be. Thanks!

**Comment by shrutiburman** [comment]
This looks like a duplicate issue.
Please try running this cmd in **Powershell ran as an Admin.**
