### ISSUE TITLE
twilio@5.2.3: decompress error

### ISSUE THREAD

**Issue by gem-ankit** [twilio/scoop-twilio-cli#43]
PS C:\Users\an.tripathi> scoop install twilio
Installing '7zip' (22.01) [64bit] from main bucket
7z2201-x64.msi (1.8 MB) [=====================================================================================] 100%
Checking hash of 7z2201-x64.msi ... ok.
Extracting 7z2201-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\22.01
Creating shim for '7z'.
Creating shim for '7zFM'.
Creating shim for '7zG'.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
Running post_install script...
'7zip' (22.01) was installed successfully!
Notes
-----
Add 7-Zip as a context menu option by running: "C:\Users\an.tripathi\scoop\apps\7zip\current\install-context.reg"
Installing 'twilio' (5.2.3) [64bit] from twilio-scoop bucket
twilio-win32-x64.tar.xz (32.6 MB) [===========================================================================] 100%
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\an.tripathi\scoop\apps\twilio\5.2.3\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.2.3\7zip.log

**Comment by shrutiburman** [comment]
This looks like a duplicate issue. Can you please try running this cmd in Powershell ran as an admin ?
