### ISSUE TITLE
twilio@5.2.3: decompress error

### ISSUE THREAD

**Issue by shaudubey** [twilio/scoop-twilio-cli#45]
PS C:\Users\dubey> scoop install twilio
WARN  Purging previous failed installation of twilio.
ERROR 'twilio' isn't installed correctly.
Removing older version (5.2.3).
'twilio' was uninstalled.
Installing 'twilio' (5.2.3) [64bit] from twilio-scoop bucket
Loading twilio-win32-x64.tar.xz from cache
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\dubey\scoop\apps\twilio\5.2.3\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.2.3\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.2.3%3a+decompress+error
PS C:\Users\dubey>

**Comment by charan678** [comment]
This looks like a duplicate issue.
Please try running this cmd in Powershell ran as an Admin.
