### ISSUE TITLE
twilio@5.2.3: decompress error

### ISSUE THREAD

**Issue by wellbolt** [twilio/scoop-twilio-cli#46]
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6                                                                                                                                                                                    > : The term '>' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the       At line:1 char:1
+ > Set-ExecutionPolicy RemoteSigned -Scope CurrentUser # Optional: Nee ...
+ ~
    + CategoryInfo          : ObjectNotFound: (>:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\wellb> > irm get.scoop.sh | iex
> : The term '>' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ > irm get.scoop.sh | iex
+ ~
    + CategoryInfo          : ObjectNotFound: (>:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Users\wellb> Set-ExecutionPolicy RemoteSigned -Scope CurrentUser # Optional: Needed to run a remote script the first time
PS C:\Users\wellb> irm get.scoop.sh | iex
Initializing...
Downloading...
Extracting...
Creating shim...
Adding ~\scoop\shims to your path.
Scoop was installed successfully!
Type 'scoop help' for instructions.
PS C:\Users\wellb>
PS C:\Users\wellb> scoop bucket add twilio-scoop https://github.com/twilio/scoop-twilio-cli
ERROR Git is required for buckets. Run 'scoop install git' and try again.
PS C:\Users\wellb> scoop install git
Installing '7zip' (22.01) [64bit] from main bucket
7z2201-x64.msi (1.8 MB) [=====================================================================================] 100%
Checking hash of 7z2201-x64.msi ... ok.
Extracting 7z2201-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\22.01
Creating shim for '7z'.
Creating shim for '7zG'.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Formats
Running post_install script...
'7zip' (22.01) was installed successfully!
Notes
-----
Add 7-Zip as a context menu option by running: "C:\Users\wellb\scoop\apps\7zip\current\install-context.reg"
Installing 'git' (2.39.0.windows.1) [64bit] from main bucket
PortableGit-2.39.0-64-bit.7z.exe (46.0 MB) [==================================================================] 100%
Checking hash of PortableGit-2.39.0-64-bit.7z.exe ... ok.
Extracting dl.7z ... done.
Linking ~\scoop\apps\git\current => ~\scoop\apps\git\2.39.0.windows.1
Creating shim for 'sh'.
Creating shim for 'bash'.
Creating shim for 'git'.
Creating shim for 'gitk'.
Creating shim for 'git-gui'.
Creating shim for 'scalar'.
Creating shim for 'tig'.
Creating shim for 'git-bash'.
Creating shortcut for Git Bash (git-bash.exe)
Creating shortcut for Git GUI (git-gui.exe)
'git' (2.39.0.windows.1) was installed successfully!
Notes
-----
Set Git Credential Manager Core by running: "git config --global credential.helper manager-core"
Checking repo... OK
The twilio-scoop bucket was added successfully.
twilio-win32-x64.tar.xz (32.6 MB) [===========================================================================] 100%
Checking hash of twilio-win32-x64.tar.xz ... ok.
Failed to extract files from C:\Users\wellb\scoop\apps\twilio\5.2.3\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.2.3\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.2.3%3a+decompress+error
PS C:\Users\wellb> scoop install twilio
WARN  Purging previous failed installation of twilio.
ERROR 'twilio' isn't installed correctly.
Removing older version (5.2.3).
'twilio' was uninstalled.
Installing 'twilio' (5.2.3) [64bit] from twilio-scoop bucket
Loading twilio-win32-x64.tar.xz from cache
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\wellb\scoop\apps\twilio\5.2.3\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.2.3\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.2.3%3a+decompress+error
PS C:\Users\wellb> scoop bucket add twilio-scoop https://github.com/twilio/scoop-twilio-cli.git
WARN  The 'twilio-scoop' bucket already exists. To add this bucket again, first remove it by running 'scoop bucket rm twilio-scoop'.
PS C:\Users\wellb> scoop bucket rm twilio-scoop
PS C:\Users\wellb> scoop bucket add twilio-scoop https://github.com/twilio/scoop-twilio-cli.git
Checking repo... OK
The twilio-scoop bucket was added successfully.
PS C:\Users\wellb> scoop install twilio
WARN  Purging previous failed installation of twilio.
ERROR 'twilio' isn't installed correctly.
Removing older version (5.2.3).
'twilio' was uninstalled.
Installing 'twilio' (5.2.3) [64bit] from twilio-scoop bucket
Loading twilio-win32-x64.tar.xz from cache
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\wellb\scoop\apps\twilio\5.2.3\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.2.3\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.2.3%3a+decompress+error
PS C:\Users\wellb>

**Comment by wellbolt** [comment]
I have no idea what I'm doing, please help. I want want to use twilio CLI on a windows PC

**Comment by charan678** [comment]
This looks like a duplicate issue.
Please try running this cmd in Powershell ran as an Admin.

**Comment by wellbolt** [comment]
Thank you @charan678

**Comment by wellbolt** [comment]
Running as admin in cmd and powershell give the same result

Microsoft Windows [Version 10.0.19044.2364]
(c) Microsoft Corporation. All rights reserved.

C:\Users\wellb>scoop install twilio
WARN  Purging previous failed installation of twilio.
ERROR 'twilio' isn't installed correctly.
Removing older version (5.3.1).
'twilio' was uninstalled.
Installing 'twilio' (5.3.1) [64bit] from twilio-scoop bucket
Loading twilio-win32-x64.tar.xz from cache
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\wellb\scoop\apps\twilio\5.3.1\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.3.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.3.1%3a+decompress+error
