### ISSUE TITLE
twilio@5.3.0: decompress error

### ISSUE THREAD

**Issue by GauravSood05** [twilio/scoop-twilio-cli#48]
Failed to extract files from C:\Users\SunnyHP\scoop\apps\twilio\5.3.0\twilio-win32-x64.tar.
Log  file:
 ~\scoop\apps\twilio\5.3.0\7zip.log

**Comment by charan678** [comment]
This looks like a duplicate issue.
Please try running this cmd in Powershell ran as an Admin.
