### ISSUE TITLE
twilio@5.3.0: decompress error

### ISSUE THREAD

**Issue by BloodShoT14** [twilio/scoop-twilio-cli#49]
scoop\apps\7zip\current\install-context.reg"
Installing 'twilio' (5.3.0) [64bit] from twilio-scoop bucket
twilio-win32-x64.tar.xz (32.6 MB) [===================] 100%
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\shagu\scoop\apps\twilio\5.3.0\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.3.0\7zip.log

**Comment by cmwky** [comment]
Also encountering this issue when running "scoop install twilio" from PowerShell ISE (non-elevated). 

Installing 'twilio' (5.3.0) [64bit] from twilio-scoop bucket
Loading twilio-win32-x64.tar.xz from cache
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\charl\scoop\apps\twilio\5.3.0\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.3.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.3.0%3a+decompress+error

**Comment by charan678** [comment]
This looks like a duplicate issue.
Please try running this cmd in Powershell ran as an Admin.
