### ISSUE TITLE
twilio@5.3.0: decompress error

### ISSUE THREAD

**Issue by Djoker-hack** [twilio/scoop-twilio-cli#50]
"Failed to extract files from  C:\Users\USER\scoop\apps\twilio\5.3.0\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.3.0\7zip.log"
the message is being printed while installing the package

**Comment by Djoker-hack** [comment]
Console output:
Failed to extract files from C:\Users\USER\scoop\apps\twilio\5.3.0\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.3.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.3.0%3a+decompress+error

**Comment by charan678** [comment]
This looks like a duplicate issue.
Please try running this cmd in Powershell ran as an Admin.
