### ISSUE TITLE
twilio@5.3.0: decompress error

### ISSUE THREAD

**Issue by ossev** [twilio/scoop-twilio-cli#51]
Installing 'twilio' (5.3.0) [64bit] from twilio-scoop bucket
Loading twilio-win32-x64.tar.xz from cache
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\oseveriche_teclogi\scoop\apps\twilio\5.3.0\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.3.0\7zip.log

**Comment by charan678** [comment]
This looks like a duplicate issue.
Please try running this cmd in Powershell ran as an Admin.
