### ISSUE TITLE
twilio@5.3.1: decompress error

### ISSUE THREAD

**Issue by hmesfin** [twilio/scoop-twilio-cli#53]
PS C:\users\hmesf> scoop install twilio
WARN  Purging previous failed installation of twilio.
ERROR 'twilio' isn't installed correctly.
Removing older version (5.3.1).
'twilio' was uninstalled.
Installing 'twilio' (5.3.1) [64bit] from twilio-scoop bucket
Loading twilio-win32-x64.tar.xz from cache
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\hmesf\scoop\apps\twilio\5.3.1\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.3.1\7zip.log

**Comment by isha689** [comment]
Hi @hmesfin, thanks for posting this.
This looks like a duplicate issue. Can you please try running this cmd in Powershell ran as an admin ?
