### ISSUE TITLE
twilio@5.3.2: decompress error

### ISSUE THREAD

**Issue by apurbanand** [twilio/scoop-twilio-cli#54]
ERROR Exit code was 2!
Failed to extract files from C:\Users\xxxx\scoop\apps\twilio\5.3.2\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.3.2\7zip.log

**Comment by shrutiburman** [comment]
This looks like a duplicate issue. Can you please try running this cmd in Powershell ran as an admin ?
