### ISSUE TITLE
twilio@5.3.3: decompress error

### ISSUE THREAD

**Issue by shailesh-sachdev** [twilio/scoop-twilio-cli#58]
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\shail\scoop\apps\twilio\5.3.3\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.3.3\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.3.3%3a+decompress+error

**Comment by shrutiburman** [comment]
This looks like a duplicate issue. Can you please try running this cmd in Powershell ran as an admin ?
