### ISSUE TITLE
twilio@5.3.3: decompress error

### ISSUE THREAD

**Issue by sameer355u** [twilio/scoop-twilio-cli#60]
PS C:\Users\Otaku> scoop install twilio
Installing '7zip' (22.01) [64bit] from main bucket
7z2201-x64.msi (1.8 MB) [=====================================================================================] 100%
Checking hash of 7z2201-x64.msi ... ok.
Extracting 7z2201-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\22.01
Creating shim for '7z'.
Creating shim for '7zFM'.
Creating shim for '7zG'.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
Running post_install script...
'7zip' (22.01) was installed successfully!
Notes
-----
Add 7-Zip as a context menu option by running: "C:\Users\Otaku\scoop\apps\7zip\current\install-context.reg"
Installing 'twilio' (5.3.3) [64bit] from twilio-scoop bucket
twilio-win32-x64.tar.xz (32.8 MB) [===========================================================================] 100%
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Otaku\scoop\apps\twilio\5.3.3\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.3.3\7zip.log

Please try again or create a new issue by using the following link and paste your console output:

**Comment by kridai** [comment]
Hi @sameer355u, thanks for reaching out.  This looks like a duplicate issue. Can you please try running this command in Powershell as an admin. Its mentioned in the doc [here](https://www.twilio.com/docs/twilio-cli/getting-started/install#scoop)
