### ISSUE TITLE
twilio@5.4.0: decompress error

### ISSUE THREAD

**Issue by kan1shq** [twilio/scoop-twilio-cli#62]
I was trying to use scoop to install Twilio-cli on windows. 
These were the steps i followed: 

In Powershell:
`Set-ExecutionPolicy RemoteSigned -Scope CurrentUser`
`irm get.scoop.sh | iex`

This resulted in "Scoop was installed successfully!"

Later, I tried to add the twilio-scoop bucket and install twilio:
`scoop bucket add twilio-scoop https://github.com/twilio/scoop-twilio-cli`

After this, the bucket was added successfully. However, when I tried to:
`scoop install twilio`

it threw the error:

Installing '7zip' (22.01) [64bit] from main bucket
7z2201-x64.msi (1.8 MB) [=====================================================================================] 100%
Checking hash of 7z2201-x64.msi ... ok.
Extracting 7z2201-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\22.01
Creating shim for '7z'.
Creating shim for '7zFM'.
Creating shim for '7zG'.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
Running post_install script...
'7zip' (22.01) was installed successfully!
Notes
-----
Add 7-Zip as a context menu option by running: "C:\Users\Kanishk Sharma\scoop\apps\7zip\current\install-context.reg"
Installing 'twilio' (5.4.0) [64bit] from twilio-scoop bucket
twilio-win32-x64.tar.xz (32.8 MB) [===========================================================================] 100%
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Kanishk Sharma\scoop\apps\twilio\5.4.0\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.4.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.4.0%3a+decompress+error

Any help in how I could resolve this issue?

**Comment by kridai** [comment]
Hi @kan1shq , Thanks for reaching out, . Can you please try running this command in Powershell as an admin. Its mentioned in the doc [here](https://www.twilio.com/docs/twilio-cli/getting-started/install#scoop)

**Comment by kan1shq** [comment]
i did that in the first place but Powershell returned an error saying "Installations as Admin are disabled by default."

**Comment by kridai** [comment]
twilio-cli scoop installation needs admin privileges. If it's disabled for you, you can try installing via the exe package. See[ this doc](https://www.twilio.com/docs/twilio-cli/getting-started/install#windows)

**Comment by kan1shq** [comment]
Yeah that works for me now. Thanks a lot!
