### ISSUE TITLE
twilio@5.4.0: decompress error

### ISSUE THREAD

**Issue by andrea193** [twilio/scoop-twilio-cli#63]
PS C:\Users\Owner> scoop install twilio
Installing 'twilio' (5.4.0) [64bit] from twilio-scoop bucket
twilio-win32-x64.tar.xz (32.8 MB) [===========================================================================] 100%
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\Owner\scoop\apps\twilio\5.4.0\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.4.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.4.0%3a+decompress+error

**Comment by kridai** [comment]
Hi @andrea193 , Could you try running this command in powershell as an admin. Its mentioned in the doc [here](https://www.twilio.com/docs/twilio-cli/getting-started/install#scoop)
