### ISSUE TITLE
twilio@5.4.0: decompress error in PowerShell

### ISSUE THREAD

**Issue by JamesD17011** [twilio/scoop-twilio-cli#64]
When trying to install Twilio CLI on a Windows 10 Home 22H2, I am seeing the following output: 

`PS C:\Users\James> scoop install twilio
Installing '7zip' (22.01) [64bit] from main bucket
7z2201-x64.msi (1.8 MB) [==========================================================================] 100%
Checking hash of 7z2201-x64.msi ... ok.
Extracting 7z2201-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\22.01
Creating shim for '7z'.
Creating shim for '7zFM'.
Creating shim for '7zG'.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
Running post_install script...
'7zip' (22.01) was installed successfully!
Notes
-----
Add 7-Zip as a context menu option by running: "C:\Users\James\scoop\apps\7zip\current\install-context.reg"
Installing 'twilio' (5.4.0) [64bit] from twilio-scoop bucket
twilio-win32-x64.tar.xz (32.8 MB) [================================================================] 100%
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\James\scoop\apps\twilio\5.4.0\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.4.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.4.0%3a+decompress+error
PS C:\Users\James> scoop install twilio
WARN  Purging previous failed installation of twilio.
ERROR 'twilio' isn't installed correctly.
Removing older version (5.4.0).
'twilio' was uninstalled.
Installing 'twilio' (5.4.0) [64bit] from twilio-scoop bucket
Loading twilio-win32-x64.tar.xz from cache
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\James\scoop\apps\twilio\5.4.0\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.4.0\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.4.0%3a+decompress+error`

**Comment by kridai** [comment]
Hi @JamesD17011  , Could you try running this command in powershell as an admin. Its mentioned in the doc [here](https://www.twilio.com/docs/twilio-cli/getting-started/install#scoop)

**Comment by JamesD17011** [comment]
Good evening
I will try this at my convenience and update the ticket

**Comment by JamesD17011** [comment]
Issue looks to be resolved. 
![Twilio5 4 0_64](https://user-images.githubusercontent.com/12768502/219074513-12321602-45f0-4008-8761-e80b9c05490f.jpg)
