### ISSUE TITLE
twilio@5.4.1: decompress error

### ISSUE THREAD

**Issue by krauses** [twilio/scoop-twilio-cli#66]
>> scoop install twilio
Checking repo... OK
The twilio-scoop bucket was added successfully.
Installing '7zip' (22.01) [64bit] from main bucket
7z2201-x64.msi (1.8 MB) [=====================================================================================] 100%
Checking hash of 7z2201-x64.msi ... ok.
Extracting 7z2201-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\22.01
Creating shim for '7z'.
Creating shim for '7zFM'.
Creating shim for '7zG'.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
Running post_install script...
'7zip' (22.01) was installed successfully!
Notes
-----
Add 7-Zip as a context menu option by running: "C:\Users\tempsteve\scoop\apps\7zip\current\install-context.reg"
Installing 'twilio' (5.4.1) [64bit] from twilio-scoop bucket
twilio-win32-x64.tar.xz (33.5 MB) [===========================================================================] 100%
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\tempsteve\scoop\apps\twilio\5.4.1\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.4.1\7zip.log

**Comment by kridai** [comment]
HI @krauses ,Could you try installation via scoop in powershell as an admin. Its mentioned in the doc [here](https://www.twilio.com/docs/twilio-cli/getting-started/install#scoop)
