### ISSUE TITLE
twilio@5.4.1: decompress error

### ISSUE THREAD

**Issue by hamhoum10** [twilio/scoop-twilio-cli#67]
ERROR Exit code was 2!
Failed to extract files from C:\Users\omriy\scoop\apps\twilio\5.4.1\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.4.1\7zip.log

**Comment by kridai** [comment]
Hi @hamhoum10 ,Could you try installation via scoop in powershell as an admin. Its mentioned in the doc [here](https://www.twilio.com/docs/twilio-cli/getting-started/install#scoop)
