### ISSUE TITLE
twilio@5.4.1: decompress error

### ISSUE THREAD

**Issue by TheCodeInjection** [twilio/scoop-twilio-cli#68]
scoop install twilio
WARN  Purging previous failed installation of twilio.
ERROR 'twilio' isn't installed correctly.
Removing older version (5.4.1).
'twilio' was uninstalled.
Installing 'twilio' (5.4.1) [64bit] from twilio-scoop bucket
Loading twilio-win32-x64.tar.xz from cache
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\areleh\scoop\apps\twilio\5.4.1\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.4.1\7zip.log

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/twilio/scoop-twilio-cli/issues/new?title=twilio%405.4.1%3a+decompress+error

**Comment by jpcc0** [comment]
Solve the problem by going into your Registry Editor --> HKEY_LOCAL_MACHINE --> SYSTEM --> ControlSet001 --> Control --> FileSystem --> Click on LongPathsEnabled and change it from 0 to 1, doing this just enables the paths to be longer. Once you click okay, close the Registry, and try again in the terminal!

**Comment by charan678** [comment]
Could you try running this command in powershell as an admin. Its mentioned in the doc [here](https://www.twilio.com/docs/twilio-cli/getting-started/install#scoop)
