### ISSUE TITLE
twilio@5.4.2: decompress error

### ISSUE THREAD

**Issue by alma765** [twilio/scoop-twilio-cli#69]
Extracting twilio-win32-x64.tar.xz ... ERROR Exit code was 2!
Failed to extract files from C:\Users\ali\scoop\apps\twilio\5.4.2\twilio-win32-x64.tar.
Log file:
  ~\scoop\apps\twilio\5.4.2\7zip.log

**Comment by kridai** [comment]
Hi @alma765 ,Could you try installation via scoop in powershell as an admin. Its mentioned in the doc [here](https://www.twilio.com/docs/twilio-cli/getting-started/install#scoop)
