### ISSUE TITLE
Twilio installation getting stuck during the extraction

### ISSUE THREAD

**Issue by MarialenaShiamma** [twilio/scoop-twilio-cli#9]
Hello, i am running in PowerShell as non-admin this command in my Downloads folder:
`scoop install twilio` 
and execution gets stuck here:
`WARN  Purging previous failed installation of twilio.
ERROR 'twilio' isn't installed correctly.
Removing older version (3.6.0).
'twilio' was uninstalled.
Installing 'twilio' (3.6.0) [64bit]
Loading twilio-win32-x64.tar.xz from cache
Checking hash of twilio-win32-x64.tar.xz ... ok.
Extracting twilio-win32-x64.tar.xz ...`

My machine is Windows. Let me know if i can give you any more info to investigate what the issue might be.

_UPDATE_: installed using the exe file at the end

**Comment by shrutiburman** [comment]
Hi @MarialenaShiamma , thanks for reaching out. Can you try running powershell as an admin, we also have a [quickstart](https://www.twilio.com/docs/twilio-cli/getting-started/install#scoop) doc for future reference.

**Comment by edinson0** [comment]
hello ready if it was a privilege problem. ty.

**Comment by MarialenaShiamma** [comment]
Sorry for the late reply, i ended up working with API in the postman and forgot about this.
And yes, all good with the admin. Thank you.
![image](https://user-images.githubusercontent.com/5478955/185558703-c713ad3c-d5d1-4458-8d50-0de878e81aa2.png)
