### ISSUE TITLE
twilio@5.8.1: hash check failed

### ISSUE THREAD

**Issue by jasalltime** [twilio/scoop-twilio-cli#93]
PS C:\Users\acer> scoop install twilio
Installing '7zip' (22.01) [64bit] from main bucket
7z2201-x64.msi (1.8 MB) [==================================================================================================================================] 100%
Checking hash of 7z2201-x64.msi ... ok.
Extracting 7z2201-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\22.01
Creating shim for '7z'.
Creating shim for '7zFM'.
Creating shim for '7zG'.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
Running post_install script...
'7zip' (22.01) was installed successfully!
Notes
-----
Add 7-Zip as a context menu option by running: "C:\Users\acer\scoop\apps\7zip\current\install-context.reg"
Installing 'twilio' (5.8.1) [64bit] from twilio-scoop bucket
twilio-win32-x64.tar.xz (40.7 MB) [========================================================================================================================] 100%
Checking hash of twilio-win32-x64.tar.xz ... ERROR Hash check failed!
App:         twilio-scoop/twilio
URL:         https://twilio-cli-prod.s3.amazonaws.com/twilio-win32-x64.tar.xz
First bytes: FD 37 7A 58 5A 00 00 04
Expected:    1d46b24cb86a5a9307edfc4a6e282e1104b4760dd48572c314fecdef1b755466
Actual:      450092d7a7d9a7aeb9e5cd4c34ea172cea6115612633e1e976033c809932964d

**Comment by shrutiburman** [comment]
Hi @jasalltime,  please re-try. We've upgraded the hash with the latest release, should be working now.

**Comment by jasalltime** [comment]
Hash is ok now, Thank you for that. 

my end scenario: 
I was using vsCode terminal, Another error came that was unable to exract `twilio-win32-x64.tar.xz`.
Then I noticed my mistake and used 'Windows Powershell(as admin)'
 Installation was smooth.
![image](https://github.com/twilio/scoop-twilio-cli/assets/88364383/40218ea9-4283-491a-a377-78755c8f0f4d)
